site_name: Baysian Inference for Biological ODEs
site_description: Primer on Bayesian inference of ecological ODE models with Python (PyMC) and Julia (Turing.jl), with case studies.
site_url: ""
repo_name: GitHub Repository
repo_url: https://github.com/B2-Bayesian-for-Biology/MCMCwithODEs_primer

theme:
  name: material
  features:
    - navigation.instant
    - navigation.sections
    - navigation.tracking
    - search.suggest
    - search.highlight
    - content.code.copy
    - toc.integrate
  palette:
    - scheme: slate
      primary: indigo
      accent: teal
  icon:
    logo: material/dna

plugins:
  - search
  - mkdocs-jupyter:
      execute: false          # don't run notebooks during build
      include_source: false   # don't show raw JSON

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.arithmatex:
      generic: true

extra_css:
  - https://cdn.jsdelivr.net/npm/katex@0.16.10/dist/katex.min.css
  - stylesheets/overrides.css

extra_javascript:
  - https://cdn.jsdelivr.net/npm/katex@0.16.10/dist/katex.min.js
  - https://cdn.jsdelivr.net/npm/katex@0.16.10/dist/contrib/auto-render.min.js
  - javascripts/katex-init.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js


nav:
  - Home: index.md
  - Education:
      - "Mini Tutorial — 10 Steps": ten-steps.md
      - Python (PyMC):
          - "Case Study 1 — Birth–death dynamics": education/python/case_study_1.ipynb
          - "Case Study 2 — Priors, noise models, diagnostics": education/python/case_study_2.ipynb
          - "Case Study 3 — Posterior inference & interpretation": education/python/case_study_3.ipynb
      - Julia (Turing.jl):
          - "Case Study 1 — Birth–death dynamics": education/julia/case_study_1.ipynb
          - "Case Study 2 — Priors, noise models, diagnostics": education/julia/case_study_2.ipynb
  - Contributors: contributors.md